
name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
  push:

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
      SYMFONY_DEPRECATIONS_HELPER: ${{matrix.symfony-deprecations-helper}}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
        dependencies:
          - "highest"
        stability:
          - "dev"
        symfony-require:
          - ""
        symfony-deprecations-helper:
          - "weak"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "pdo_sqlite"

      - name: "Globally install symfony/flex"
        run: "composer global require --no-progress --no-scripts --no-plugins symfony/flex"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"